server:
  port: 9090

spring:
  application:
    name: dcloud-aipan

  # db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dcloud_aipan?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: wshen@163.com
  #redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 000415

# mybatis-plus??
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: del
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# minio
minio:
  endpoint: http://192.168.127.131:9000
  access-key: minio_root
  access-secret: minio_123456
  bucket-name: ai-pan
  avatar-bucket-name: avatar
